### PR TITLE
Make `cbLibPath` relocatable on sysimages, with RelocatableFolders.

### PR DESCRIPTION
**Pull request by ven-k**
On relocated sysimages, `cbLibPath` 's value has hardcoded source system's path. With RelocFolders, it will be relocatable.

### CODE REVIEW

**Comment by ThummeTo** [comment]
This is cool, thanks.
I will think about if we need to do that at other places, too.

**Comment by ashutosh-b-b** [comment]
@ThummeTo can we get a backport release with this fix for the version `0.12.1`

**Comment by ThummeTo** [comment]
Yes, we can do that. I'm on it ...

**Comment by ThummeTo** [comment]
Please check if branch v0.12.3 is what you need.
The changes v0.12.2 to v0.12.3 can be seen [here](https://github.com/ThummeTo/FMIImport.jl/compare/2110a94..81b5fc7).

**Comment by ashutosh-b-b** [comment]
Yes, that is the change we need. Thanks a lot!

**Comment by ThummeTo** [comment]
You're welcome!
Registration in progress!

**Pull request merged**
