### PR TITLE
Callbacks for Linux and build automation

### PR DESCRIPTION
**Pull request by AnHeuermann**
## Description

I need the external C logging function to debug some Linux FMUs. Because FMIImport.jl is missing them I added the binaries.

## Changes

  - Replaced Code::Blocks project file with CMake project (mainly because I don't know how to use it for multi-platform projects...)
  - Added simple C test program for callback functions.
  - Added workflow `callbackFunctions.yml` to build and test callback functions on Linux, Windows and Mac.
    The script is not perfect but will upload the artifacts. At the moment they have to be downloaded and added to the binaries 
 directory manually. It's possible to automate, but I haven't found a reliable way that never runs into an endless loop or creates more commits then wanted.
  - I made the logs colorful to spot errors faster.
  - `fmi2Instantiate!` can now use `externalCallbacks=true` for win64, linux64 and darwin64.
  - Added test for logging with `fmi2Instantiate!()` and `externalCallbacks=true`.

### CODE REVIEW

**Comment by ThummeTo** [comment]
Dear @AnHeuermann ,
thank you again! One last question (I will then merge and trigger a release): Shouldn't we only rebuild binaries if the source files change? I think there was an option in Github-Actions to check for changed files/directories before triggering.

What do you say? Best regards!

**Comment by AnHeuermann** [comment]
I tried to add something like that but it wasn't really working for me. If you know how to add it we could try again.

**Comment by ThummeTo** [comment]
@stoljarjo

**Comment by stoljarjo** [comment]
Can be closed because new PR #41

**Comment by ThummeTo** [comment]
Merged together with #41

**Pull request closed without merging**
