### PR TITLE
Change `fmi2Reset` logic

### PR DESCRIPTION
**Pull request by manuelbb-upb**
I am not sure if `fmi2Reset` works according to spec. I had an FMU2 with `fmu.executionConfig = FMICore.FMU2_EXECUTION_CONFIGURATION_RESET` and tried repeated calls to `prepareSolveFMU` which did not work because no reset was performed.

With this pull request we allow resets almost always, except in fatal states.

### CODE REVIEW

**Comment by JoKircher** [comment]
@ThummeTo this PR looks fine to me. It's up to you, if we want to add this functionality to FMIImport. But @manuelbb-upb is right, according to the spec, fmi2Reset should be able to called in all states except fmi2Fatal. 
image

**Comment by JoKircher** [comment]
@ThummeTo but please be aware that also a new version of the callbackfunction .dll was part of the PR

**Comment by manuelbb-upb** [comment]
Thank's for looking into it.

> @ThummeTo but please be aware that also a new version of the callbackfunction .dll was part of the PR

Oops, did not notice. The file mode was changed automatically. I can set up my git config to ignore file mode changes in the future. In this case, it should not matter, I think.

**Comment by manuelbb-upb** [comment]
Done :)

**Pull request merged**
