### PR TITLE
Added functions for getting FMU metadata

### PR DESCRIPTION
**Pull request by sathvikbhagavan**
Added functions for getting input, output, state, parameter and derivative names from FMU modelDescription.

### CODE REVIEW

**Review by sharanry — COMMENTED** [review]
Can the tests check not just length of the result but the actually values of the results?

**Comment by ThummeTo** [comment]
> Can the tests check not just length of the result but the actually values of the results?

In general, we want to accomplish that by implementing the FMI-CrossChecks from ModelicaAssoctation. This repo is currently archived and will be replaced by a successor soon, so it will still take some time.

As workaround, we are checking for simulation results/states at `t=0` (everything initialized correctly?) and `t=end` (last simulation time step). This is not perfect, but changes are high the simulation between worked correctly if `t=end` is not a stable equilibrium or similar of the system. And as said, it's only a workaround until we have the new cross-checks. SO I would suggest to check results at least at simulation start and stop?

**Comment by ThummeTo** [comment]
BTW: @[sathvikbhagavan](https://github.com/sathvikbhagavan) much appreciated! Let me know if you are ready to review/test :-)

**Comment by ThummeTo** [comment]
> Can the tests check not just length of the result but the actually values of the results?

Ah now I see what you meant, in fact you are right. The tests are only checking for the length of the name-arrays instead of checking theire actual content. This is not good... I will fix this. And if it is ok @sathvikbhagavan I would rename the functions to better fit the tone of the FMI-command-set?

**Comment by sathvikbhagavan** [comment]
I added some tests for checking the values of the arrays yesterday. But if you think more tests are required, please feel free to add them. I am fine with renaming functions according to the FMI convention.

**Comment by sathvikbhagavan** [comment]
I saw the code for ```fmi2ValueReferenceToString``` and ```fmi2StringToValueReference```. The functions ```fmi2GetNamesToValueReference``` and ```fmi2GetValueRefenceToName``` are similar but gives out a dictionary for all modelVariables.

**Pull request merged**
